create book entity and some services to save and getAll books from db…
don-bigdad/SpringBoot-Book-Shop pull request #1
Opened 2023-10-12 18:49 UTC by don-bigdad

… using SpringBoot framework

2023-10-12 19:52 UTC, mmosii requested changes
Great job! Have few minor suggestions

2023-10-12 19:52 UTC, mmosii commented on src/main/java/com/example/springbootbookshop/entity/Book.java
> +public class Book {
better to change name of table to "books"

2023-10-12 19:52 UTC, mmosii commented on src/main/java/com/example/springbootbookshop/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can`t save book in DB:" + book, e);
maybe custom exception will be better in this case

2023-10-12 19:52 UTC, mmosii commented on src/main/java/com/example/springbootbookshop/repository/impl/BookRepositoryImpl.java
> +        }
maybe custom exception will be better in this case

2023-10-13 06:06 UTC, Andriy-dz approved these changes

2023-10-13 06:06 UTC, Andriy-dz commented on .gitignore
> +src/test/resources/application.properties
why u add this?)

2023-10-13 06:06 UTC, Andriy-dz commented on pom.xml
> +            </dependency>
set the correct number of spaces

2023-10-15 19:40 UTC, merged