implement order logic
don-bigdad/SpringBoot-Book-Shop pull request #12
Opened 2023-11-27 14:49 UTC by don-bigdad

2023-12-01 09:43 UTC, liliia-ponomarenko requested changes
Good job! Let’s improve your solution ;)

2023-12-01 09:43 UTC, liliia-ponomarenko commented on src/main/java/com/example/springbootbookshop/controller/OrderController.java
> +        return user.getId();
can be an inline variable

2023-12-01 09:43 UTC, liliia-ponomarenko commented on src/main/java/com/example/springbootbookshop/controller/OrderController.java
> +    public void updateStatus(@Positive @PathVariable Long orderId,
Positive doesn’t  work without Validated

2023-12-01 09:43 UTC, liliia-ponomarenko commented on src/main/java/com/example/springbootbookshop/controller/OrderController.java
> +    public Set<OrderDto> showOrderHistory(Authentication authentication) {
```suggestion
    public Set<OrderDto> getOrderHistory(Authentication authentication) {
```

2023-12-01 09:43 UTC, liliia-ponomarenko commented on src/main/java/com/example/springbootbookshop/controller/OrderController.java
> +    public OrderItemDto showOrderItem(Authentication authentication,
the same

2023-12-01 09:43 UTC, liliia-ponomarenko commented on src/main/java/com/example/springbootbookshop/entity/Order.java
> +            cascade = CascadeType.REMOVE)
Maybe  ALL?

2023-12-01 09:43 UTC, liliia-ponomarenko commented on src/main/java/com/example/springbootbookshop/mapper/OrderItemMapper.java
> +
```suggestion
```

2023-12-01 09:43 UTC, liliia-ponomarenko commented on src/main/java/com/example/springbootbookshop/repository/OrderItemsRepository.java
> +    Optional<OrderItemDto> findByOrderAndId(Order order, Long id);
Why do you return Dto from DB?

2023-12-01 09:43 UTC, liliia-ponomarenko commented on src/main/java/com/example/springbootbookshop/repository/OrderItemsRepository.java
> +    Set<OrderItemDto> findByOrder(Order order);
the same

2023-12-01 09:43 UTC, liliia-ponomarenko commented on src/main/java/com/example/springbootbookshop/service/impl/CartServiceImpl.java
> +        }
Can you replace it using a ternary operator?

2023-12-01 09:43 UTC, liliia-ponomarenko commented on src/main/java/com/example/springbootbookshop/service/impl/OrderServiceImpl.java
> +        return cartMapper.toDto(cart);
Let’s divide this logic by some private methods for increasing readability

2023-12-01 09:43 UTC, liliia-ponomarenko commented on src/main/java/com/example/springbootbookshop/service/impl/OrderServiceImpl.java
> +                        "User doen`t have order with id: " + orderId));
Why do you need this logic? Can you create a request to DB and find orderItem by input parameters?

2023-12-01 09:43 UTC, liliia-ponomarenko commented on src/main/java/com/example/springbootbookshop/service/impl/OrderServiceImpl.java
> +                        + " for user with id: " + userId));
the same

2023-12-01 09:43 UTC, liliia-ponomarenko commented on src/main/java/com/example/springbootbookshop/service/impl/OrderServiceImpl.java
> +    public Set<OrderDto> showAllOrders(Long userId) {
```suggestion
    public Set<OrderDto> getAllOrders(Long userId) {
```

2023-12-01 09:43 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/09-add-orders-table.yaml
> +            onDelete: CASCADE
add one empty line (check other files)

2023-12-01 09:43 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/10-create-orders-items-table.yaml
> +            constraintName: FK_order_items_book
Do you have the same constraints for the entity? Should you have it?

2023-12-01 09:43 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/09-add-orders-table.yaml
> +        - addForeignKeyConstraint:
the same

2023-12-04 08:17 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-12-04 08:17 UTC, Elena-Bruyako commented on src/main/java/com/example/springbootbookshop/entity/OrderItem.java
> +    @ManyToOne(fetch = FetchType.LAZY)
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2023-12-04 08:17 UTC, Elena-Bruyako commented on src/main/java/com/example/springbootbookshop/repository/OrderRepository.java
> +
```suggestion
```

2023-12-04 08:17 UTC, Elena-Bruyako commented on src/main/java/com/example/springbootbookshop/controller/OrderController.java
> +    public Set<OrderDto> getOrderHistory(Authentication authentication) {
Pageable pageable ?

2023-12-04 09:42 UTC, liliia-ponomarenko approved these changes
Great 😊

2023-12-04 09:43 UTC, merged