createDto Mapper and controller
don-bigdad/SpringBoot-Book-Shop pull request #2
Opened 2023-10-15 22:17 UTC by don-bigdad

2023-10-16 09:11 UTC, teract10s approved these changes
Good job

2023-10-16 09:11 UTC, teract10s commented on src/main/java/com/example/springbootbookshop/controller/BookController.java
> +    @GetMapping(value = "/{id}")
you can left only @GetMapping("/{id}") without param value

2023-10-16 09:11 UTC, teract10s commented on src/main/java/com/example/springbootbookshop/controller/BookController.java
> +@RequestMapping(value = "/books")
here the same

2023-10-16 09:11 UTC, teract10s commented on src/main/java/com/example/springbootbookshop/mapper/BookMapper.java
> +    Book bookToModel(CreateBookRequestDto bookDto);
Maybe rename it and left just "toModel"

2023-10-17 06:45 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-10-17 06:45 UTC, NazarSmith228 commented on checkstyle.xml
> +
try not to modify existing code when possible :)

2023-10-17 06:45 UTC, NazarSmith228 commented on src/main/java/com/example/springbootbookshop/config/MapperConfig.java
> +public class MapperConfig {
it is better to specify `@MapperConfig` directly above the mapper class

2023-10-17 06:45 UTC, NazarSmith228 commented on src/main/java/com/example/springbootbookshop/dto/BookDto.java
> +public class BookDto {
it is better to use records for DTO

if your Checkstyle fires at it - upgrade `maven-checkstyle-plugin` to 3.3.0

2023-10-17 06:45 UTC, NazarSmith228 commented on src/main/java/com/example/springbootbookshop/dto/CreateBookRequestDto.java
> +public class CreateBookRequestDto {
it is better to use records for DTO

if your Checkstyle fires at it - upgrade `maven-checkstyle-plugin` to 3.3.0

2023-10-17 06:45 UTC, NazarSmith228 commented on src/main/java/com/example/springbootbookshop/mapper/BookMapper.java
> +    Book bookToModel(CreateBookRequestDto bookDto);
I would recommend `toBook`

2023-10-17 06:45 UTC, NazarSmith228 commented on src/main/java/com/example/springbootbookshop/repository/impl/BookRepositoryImpl.java
> +                    .uniqueResult());
you can replace it with a simpler approach:
```
Optional.ofNullable(sessionFactory.fromSession(s -> s.find(Book.class, id)));
```

2023-10-17 06:45 UTC, NazarSmith228 commented on src/main/java/com/example/springbootbookshop/repository/impl/BookRepositoryImpl.java
> +            throw new DataProcessingException("Can`t get Book from DB with id: "
I believe you should throw `EntityNotFoundException` here

2023-10-17 06:45 UTC, NazarSmith228 commented on src/main/java/com/example/springbootbookshop/service/impl/BookServiceImpl.java
> +                        "Can`t get book with id from DB: " + id)));
we can make use of Optional's `map` method here:
```
return repository.findById(id)
            .map(bookMapper::toDto)
            .orElseThrow(...);
```

2023-10-17 13:53 UTC, Elena-Bruyako approved these changes

2023-10-17 18:04 UTC, merged