Pagination sorting dev
don-bigdad/SpringBoot-Book-Shop pull request #5
Opened 2023-10-19 21:37 UTC by don-bigdad

2023-10-20 14:52 UTC, dmytrocherepov approved these changes

2023-10-20 14:52 UTC, dmytrocherepov commented on src/main/java/com/example/springbootbookshop/controller/BookController.java
> +    @Operation(summary = "Get all books from DB")
Maybe you should add description to your Operations , but i suppose that it is up you

2023-10-21 15:51 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-10-21 15:51 UTC, NazarSmith228 commented on pom.xml
> +            <version>3.1.4</version>
you may skip version here

2023-10-21 15:51 UTC, NazarSmith228 commented on src/main/java/com/example/springbootbookshop/controller/BookController.java
> +    public BookDto getBookById(@RequestBody @Valid CreateBookRequestDto bookDto,
is it really `get`?)

2023-10-21 15:51 UTC, NazarSmith228 commented on src/main/java/com/example/springbootbookshop/controller/BookController.java
> +    public List<BookDto> getAll(Pageable pageable) {
makes sense to add `@PageableDefault`

2023-10-21 15:51 UTC, NazarSmith228 commented on src/main/java/com/example/springbootbookshop/controller/BookController.java
> +    public void deleteBookById(@PathVariable Long id) {
you've added `@Validated` but you don't validate `@PathVariable` :)

```suggestion
    public void deleteBookById(@PathVariable @Positive Long id) {
```

2023-10-21 15:51 UTC, NazarSmith228 commented on src/main/java/com/example/springbootbookshop/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(ex.getLocalizedMessage(), HttpStatus.BAD_REQUEST);
```suggestion
        return new ResponseEntity<>(ex.getLocalizedMessage(), HttpStatus.NOT_FOUND);
```

2023-10-22 14:35 UTC, NazarSmith228 approved these changes
LGTM

2023-10-22 15:28 UTC, merged