Order dev
don-bigdad/SpringBoot-Book-Shop pull request #9
Opened 2023-11-15 18:47 UTC by don-bigdad

2023-11-15 22:06 UTC, OlehReex approved these changes
Agree! Just a few comments 😉

2023-11-15 22:06 UTC, OlehReex commented on src/main/java/com/example/springbootbookshop/controller/OrderController.java
> +                                       @PathVariable Long orderId) {
you can add  here `@Positive` validation too

2023-11-15 22:06 UTC, OlehReex commented on src/main/java/com/example/springbootbookshop/controller/OrderController.java
> +        return orderService.save(getUserId(authentication), requestOrderDto);
When you make order you should return response with shippind adress. Create one more DTO smth like `CreateOrderRespponseDto`

2023-11-15 22:06 UTC, OlehReex commented on src/main/java/com/example/springbootbookshop/controller/OrderController.java
> +        orderService.updateOrderStatus(orderId, updateStatus);
Here you should return response with status

2023-11-15 22:06 UTC, OlehReex commented on src/main/java/com/example/springbootbookshop/repository/OrderItemsRepository.java
> +    Set<OrderItemDto> findByOrder(Order order);
Why you return DTO's from database? You should return OrderItem and map it in mapper to OrderItemDto if you need

2023-11-15 22:06 UTC, OlehReex commented on src/main/java/com/example/springbootbookshop/service/impl/OrderServiceImpl.java
> +        Order order = new Order();
it's better to create new method for creating new order (single responsibility)

2023-11-18 14:20 UTC, NazarSmith228 requested changes
Seems that this PR contains changes for both Shopping Cart and Order. Please split since it is way too big to review

2023-11-27 14:51 UTC, closed without merging